apiVersion: v1
kind: Pod
metadata:
  name: motion-detector 
spec:
  runtimeClassName: nvidia
  containers:
  - name: motion-detector
    image: 10.31.81.1:5000/seonghapark/motion-detector:0.3.0
    args:
    - --input
    - http://playback-server:8090/bottom/image.jpg
