apiVersion: v1
kind: Pod
metadata:
  name: motion-detection 
spec:
  runtimeClassName: nvidia
  containers:
  - name: motion-detection
    image: 10.31.81.1:5000/seonghapark/motion-detection:0.2.1
    args:
    - --input
    - http://playback-server:8090/bottom/image.jpg
