apiVersion: v1
kind: Pod
metadata:
  name: object-counter
spec:
  runtimeClassName: nvidia
  containers:
  - name: object-counter
    image: 10.31.81.1:5000/yonghokim/object-counter:0.5.1
    args:
    - -stream
    - http://playback-server.default.svc.cluster.local:8090/bottom/image.jpg
