apiVersion: v1
kind: Pod
metadata:
  name: surface-water-classifier 
spec:
  runtimeClassName: nvidia
  containers:
  - name: surface-water-classifier
    image: 10.31.81.1:5000/seonghapark/surface-water-classifier:0.0.5
    args:
    - -stream
    - http://playback-server:8090/bottom/image.jpg
    - -sampling-interval
    - "0"
