apiVersion: v1
kind: Pod
metadata:
  name: traffic-state 
spec:
  runtimeClassName: nvidia
  containers:
  - name: traffic-state
    image: 10.31.81.1:5000/seonghapark/traffic-state:0.1.1
    args:
    - -stream
    - http://playback-server:8090/bottom/image.jpg
    - -duration
    - "30"
    - -roi-area
    - "40"
    - -roi-length
    - "10"
    - -roi-coordinates
    - 0.25,0.44 0.44,0.3 0.8,0.44 0.81,0.74
    - -loi-coordinates
    - 0.25,0.44 0.44,0.3
    - -sampling-interval
    - "0"

