---
- name: Setup nvidia runtime 
  hosts: test_node
  become: true
  gather_facts: no

  tasks:
  - name: Install nvidia container toolkit
    shell: curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list; apt-get update; apt-get install -y nvidia-container-toolkit

  - name: Set nvidia runtime
    k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      namespace: "{{ k3s_namespace }}"
      definition: "{{ lookup('template', 'kubernetes/set-nvidia-runtime.yaml') | from_yaml_all }}"