---
- name: Setup Grafana Agent 
  hosts: test_node
  become: true
  gather_facts: no

  tasks:
  - name: Download Grafana CRDs
    shell: wget -P /tmp/ 'https://raw.githubusercontent.com/grafana/agent/main/operations/agent-static-operator/crds/{{ item }}'; kubectl apply -f /tmp/{{ item }}
    with_items:
    - monitoring.coreos.com_podmonitors.yaml  
    - monitoring.coreos.com_probes.yaml
    - monitoring.coreos.com_servicemonitors.yaml
    - monitoring.grafana.com_grafanaagents.yaml
    - monitoring.grafana.com_integrations.yaml
    - monitoring.grafana.com_logsinstances.yaml
    - monitoring.grafana.com_metricsinstances.yaml
    - monitoring.grafana.com_podlogs.yaml

  - name: Get Node Name
    shell: "kubectl get node"
    register: node_name

  # required for jetson-exporter
  - name: Label GPU
    shell: "kubectl label nodes {{ node_name.stdout_lines[1].split(' ')[0] }} resource.gpu=true"

  - name: Deploy Grafana Agent objects
    shell: echo '{{ lookup("template", "kubernetes/{{ item }}") }}' > /tmp/{{ item }}; kubectl apply -n {{ k3s_namespace }} -f /tmp/{{ item }} --validate=false
    with_items:
    - jetson-exporter.yaml
    - pod-monitor.yaml
    - grafana-operator.yaml.j2
    - grafana-agent.yaml.j2
    - grafana-operator-scrape.yaml.j2
  