---
- name: Setup Grafana Agent 
  hosts: test_node
  become: true
  gather_facts: no

  tasks:
  - name: Download Grafana CRDs
    shell: wget -P /tmp/ 'https://raw.githubusercontent.com/grafana/agent/main/operations/agent-static-operator/crds/{{ item }}'; kubectl apply -f /tmp/{{ item }}
    with_items:
    - monitoring.coreos.com_podmonitors.yaml  
    - monitoring.coreos.com_probes.yaml
    - monitoring.coreos.com_servicemonitors.yaml
    - monitoring.grafana.com_grafanaagents.yaml
    - monitoring.grafana.com_integrations.yaml
    - monitoring.grafana.com_logsinstances.yaml
    - monitoring.grafana.com_metricsinstances.yaml
    - monitoring.grafana.com_podlogs.yaml

  - name: Get Node Name
    shell: "kubectl get node"
    register: node_name

  # required for jetson-exporter
  - name: Label GPU
    shell: "kubectl label nodes {{ node_name.stdout_lines[1].split(' ')[0] }} resource.gpu=true"

  - name: Deploy Jetson Exporter in Kubernetes
    k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      namespace: "{{ k3s_namespace }}"
      definition: "{{ lookup('template', 'kubernetes/jetson-exporter.yaml') | from_yaml_all }}"

  - name: Deploy Jetson Exporter Pod Monitor
    k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      namespace: "{{ k3s_namespace }}"
      definition: "{{ lookup('template', 'kubernetes/pod-monitor.yaml') | from_yaml_all }}"

  - name: Install Grafana operator
    k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      namespace: "{{ k3s_namespace }}"
      definition: "{{ lookup('template', 'kubernetes/grafana-operator.yaml.j2') | from_yaml_all }}"

  - name: Install Grafana agent
    k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      namespace: "{{ k3s_namespace }}"
      definition: "{{ lookup('template', 'kubernetes/grafana-agent.yaml.j2') | from_yaml_all }}"

  - name: Deploy Grafana operator scrapers
    k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      namespace: "{{ k3s_namespace }}"
      definition: "{{ lookup('template', 'kubernetes/grafana-operator-scrape.yaml.j2') | from_yaml_all }}"
